# Step1: Import Modules

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Step2: import dataset

In [3]:
event_type = pd.read_csv('cvs data files/event_type.csv')
log_feature = pd.read_csv('cvs data files/log_feature.csv')
resource_type = pd.read_csv('cvs data files/resource_type.csv')
severity_type = pd.read_csv('cvs data files/severity_type.csv')

In [4]:
train = pd.read_csv('cvs data files/train.csv')
test = pd.read_csv('cvs data files/test.csv')

In [5]:
print(event_type.id.nunique(), log_feature.id.nunique(), resource_type.id.nunique(), severity_type.id.nunique())
print(event_type.id.unique())
print(log_feature.id.unique())
print(resource_type.id.unique())
print(severity_type.id.unique())
#print(severity_type.id.sort_values())
print(severity_type.shape)
print(event_type.shape)
print(log_feature.shape)
print(resource_type.shape)

18552 18552 18552 18552
[6597 8011 2597 ... 6488  878 4464]
[6597 8011 2597 ... 6488  878 4464]
[6597 8011 2597 ... 6488  878 4464]
[6597 8011 2597 ... 6488  878 4464]
(18552, 2)
(31170, 2)
(58671, 3)
(21076, 2)


In [6]:
print(train.id.nunique(), test.id.nunique())
print(train.id.unique())
#print(test.id.unique())
print(train.id.shape)
print(test.id.shape)

7381 11171
[14121  9320 14394 ... 14111 15189 17067]
(7381,)
(11171,)


In [7]:
train[train['id'] == 14121]

id      location  fault_severity
0  14121  location 118               1

In [8]:
print(event_type.head(3))
print(' ')
print(log_feature.head(3))
print(' ')
print(resource_type.head(3))
print(' ')
print(severity_type.head(3))

     id     event_type
0  6597  event_type 11
1  8011  event_type 15
2  2597  event_type 15
 
     id log_feature  volume
0  6597  feature 68       6
1  8011  feature 68       7
2  2597  feature 68       1
 
     id    resource_type
0  6597  resource_type 8
1  8011  resource_type 8
2  2597  resource_type 8
 
     id    severity_type
0  6597  severity_type 2
1  8011  severity_type 2
2  2597  severity_type 2


In [9]:
print(train.head(3))
print(' ')
print(test.head(3))

      id      location  fault_severity
0  14121  location 118               1
1   9320   location 91               0
2  14394  location 152               1
 
      id      location
0  11066  location 481
1  18000  location 962
2  16964  location 491


# Step 3: data preprocessing(understanding)

# Step 4: Data merging to create a single record(CAR)

In [10]:
data = pd.merge(event_type, log_feature)
data = pd.merge(data, resource_type)
data = pd.merge(data, severity_type)

In [11]:
data.head(3)

id     event_type log_feature  volume    resource_type    severity_type
0  6597  event_type 11  feature 68       6  resource_type 8  severity_type 2
1  8011  event_type 15  feature 68       7  resource_type 8  severity_type 2
2  2597  event_type 15  feature 68       1  resource_type 8  severity_type 2

In [12]:
print(data.shape)
print(data.id.nunique())

(146423, 6)
18552


In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146423 entries, 0 to 146422
Data columns (total 6 columns):
id               146423 non-null int64
event_type       146423 non-null object
log_feature      146423 non-null object
volume           146423 non-null int64
resource_type    146423 non-null object
severity_type    146423 non-null object
dtypes: int64(2), object(4)
memory usage: 7.8+ MB


# Step 5: Remove text from variables

In [14]:
data.dtypes

id                int64
event_type       object
log_feature      object
volume            int64
resource_type    object
severity_type    object
dtype: object

In [15]:
data['event_type'] = data['event_type'].apply(lambda x: x[11:])
data['log_feature'] = data['log_feature'].apply(lambda x: x[8:])
data['resource_type'] = data['resource_type'].apply(lambda x: x[14:])
data['severity_type'] = data['severity_type'].apply(lambda x: x[14:])

In [16]:
data.head()

id event_type log_feature  volume resource_type severity_type
0  6597         11          68       6             8             2
1  8011         15          68       7             8             2
2  2597         15          68       1             8             2
3  5022         15         172       2             8             1
4  5022         15          56       1             8             1

In [17]:
data[data['id'] == 14121]

id event_type log_feature  volume resource_type severity_type
18821  14121         34         312      19             2             2
18822  14121         34         232      19             2             2
18823  14121         35         312      19             2             2
18824  14121         35         232      19             2             2

In [18]:
data.dtypes

id                int64
event_type       object
log_feature      object
volume            int64
resource_type    object
severity_type    object
dtype: object

# Step 6: Drop "fault_severity" from train dataset as it is the target variable 

In [19]:
# del train['fault_severity']

In [20]:
train.head(3)

id      location  fault_severity
0  14121  location 118               1
1   9320   location 91               0
2  14394  location 152               1

In [21]:
train['location'] = train['location'].apply(lambda x: x[9: ])

In [22]:
train.head(3)

id location  fault_severity
0  14121      118               1
1   9320       91               0
2  14394      152               1

In [23]:
data.head()

id event_type log_feature  volume resource_type severity_type
0  6597         11          68       6             8             2
1  8011         15          68       7             8             2
2  2597         15          68       1             8             2
3  5022         15         172       2             8             1
4  5022         15          56       1             8             1

In [24]:
print(data.shape)
print(data.id.nunique())

(146423, 6)
18552


In [25]:
print(train.shape)
print(train.id.nunique())

(7381, 3)
7381


In [26]:
df = pd.merge(data, train)

In [27]:
print(df.shape)
print(df.id.nunique())

(61839, 8)
7381


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61839 entries, 0 to 61838
Data columns (total 8 columns):
id                61839 non-null int64
event_type        61839 non-null object
log_feature       61839 non-null object
volume            61839 non-null int64
resource_type     61839 non-null object
severity_type     61839 non-null object
location          61839 non-null object
fault_severity    61839 non-null int64
dtypes: int64(3), object(5)
memory usage: 4.2+ MB


# Step 8: Convert Categoricals using Get_Dummies

In [29]:
car = df.copy()

In [30]:
del car['fault_severity']

In [31]:
df_dummies = pd.get_dummies(car, drop_first=True)

In [32]:
df_dummies.shape

(61839, 1321)

In [33]:
df_dummies.head(3)

id  volume  event_type_10  event_type_11  event_type_12  event_type_13  \
0  8011       7              0              0              0              0   
1  2588       9              0              0              0              0   
2  2588       5              0              0              0              0   

   event_type_14  event_type_15  event_type_18  event_type_19      ...       \
0              0              1              0              0      ...        
1              0              1              0              0      ...        
2              0              1              0              0      ...        

   location_987  location_989  location_99  location_990  location_991  \
0             0             0            0             0             0   
1             0             0            0             0             0   
2             0             0            0             0             0   

   location_994  location_995  location_996  location_998  location_999  
0             0             0             0             0             0  
1             0             0             0             0             0  
2             0             0             0             0             0  

[3 rows x 1321 columns]

In [34]:
df_after_groupby = df_dummies.groupby(df_dummies.id, sort=False).sum()

In [35]:
df_after_groupby.shape

(7381, 1321)

In [36]:
df_after_groupby.head()

id  volume  event_type_10  event_type_11  event_type_12  \
id                                                                 
8011   8011       7            0.0            0.0            0.0   
2588  20704      68            0.0            4.0            0.0   
4848  48480      70            0.0            5.0            0.0   
6914  13828      22            0.0            1.0            0.0   
5337  42696      50            0.0            4.0            0.0   

      event_type_13  event_type_14  event_type_15  event_type_18  \
id                                                                 
8011            0.0            0.0            1.0            0.0   
2588            0.0            0.0            4.0            0.0   
4848            0.0            0.0            5.0            0.0   
6914            0.0            0.0            1.0            0.0   
5337            0.0            0.0            4.0            0.0   

      event_type_19      ...       location_987  location_989  location_99  \
id                       ...                                                 
8011            0.0      ...                0.0           0.0          0.0   
2588            0.0      ...                0.0           0.0          0.0   
4848            0.0      ...                0.0           0.0          0.0   
6914            0.0      ...                0.0           0.0          0.0   
5337            0.0      ...                0.0           0.0          0.0   

      location_990  location_991  location_994  location_995  location_996  \
id                                                                           
8011           0.0           0.0           0.0           0.0           0.0   
2588           0.0           0.0           0.0           0.0           0.0   
4848           0.0           0.0           0.0           0.0           0.0   
6914           0.0           0.0           0.0           0.0           0.0   
5337           0.0           0.0           0.0           0.0           0.0   

      location_998  location_999  
id                                
8011           0.0           0.0  
2588           0.0           0.0  
4848           0.0           0.0  
6914           0.0           0.0  
5337           0.0           0.0  

[5 rows x 1321 columns]

In [37]:
# how to check the data is noralized? - no need for classification 

In [38]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [39]:
# sns.pairplot(df_after_groupby)

In [40]:
import numpy as np

In [41]:
# plt.hist(np.log(df_after_groupby['volume']))

# Modeling
- classification prediction
- classification model including: Logistic Regression, naive-Bayes, decision trees, support vector machines, k nearest neighbors, Random Forest, Gradient boosting, Neural networks, ensemble methods

In [42]:
x = df_after_groupby.copy()

In [43]:
x.head(3)

id  volume  event_type_10  event_type_11  event_type_12  \
id                                                                 
8011   8011       7            0.0            0.0            0.0   
2588  20704      68            0.0            4.0            0.0   
4848  48480      70            0.0            5.0            0.0   

      event_type_13  event_type_14  event_type_15  event_type_18  \
id                                                                 
8011            0.0            0.0            1.0            0.0   
2588            0.0            0.0            4.0            0.0   
4848            0.0            0.0            5.0            0.0   

      event_type_19      ...       location_987  location_989  location_99  \
id                       ...                                                 
8011            0.0      ...                0.0           0.0          0.0   
2588            0.0      ...                0.0           0.0          0.0   
4848            0.0      ...                0.0           0.0          0.0   

      location_990  location_991  location_994  location_995  location_996  \
id                                                                           
8011           0.0           0.0           0.0           0.0           0.0   
2588           0.0           0.0           0.0           0.0           0.0   
4848           0.0           0.0           0.0           0.0           0.0   

      location_998  location_999  
id                                
8011           0.0           0.0  
2588           0.0           0.0  
4848           0.0           0.0  

[3 rows x 1321 columns]

In [44]:
y = train['fault_severity']
y.shape

(7381,)

## split train and test dataset

In [45]:
from sklearn.model_selection import train_test_split as tts
x_train, x_test, y_train, y_test = tts(x, y, test_size =.2, random_state=10)

## Import algorithm

In [46]:
# from sklearn.linear_model import LinearRegression as lr this is for regression
from sklearn.linear_model import LogisticRegression   # actually classifciation 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import GradientBoostingClassifier 

In [47]:
l = LogisticRegression()
d = DecisionTreeClassifier()
r = RandomForestClassifier()
g = GradientBoostingClassifier()

In [48]:
lr = l.fit(x_train, y_train)
dr = d.fit(x_train, y_train)
rr = r.fit(x_train, y_train)
gr = g.fit(x_train, y_train)

### Print socre matrix

In [49]:
print('Logistic Regression score: ', lr.score(x_train, y_train))
print('Decision Tree: ', dr.score(x_train, y_train))
print('Random Forest: ', rr.score(x_train, y_train))
print('Gradient boosting: ',gr.score(x_train, y_train))

Logistic Regression score:  0.6510840108401084
Decision Tree:  1.0
Random Forest:  0.9568089430894309
Gradient boosting:  0.6695460704607046


In [50]:
print('Logistic Regression score: ', lr.score(x_test, y_test))
print('Decision Tree: ', dr.score(x_test, y_test))
print('Random Forest: ', rr.score(x_test, y_test))
print('Gradient boosting: ',gr.score(x_test, y_test))

Logistic Regression score:  0.6330399458361544
Decision Tree:  0.5172647257955315
Random Forest:  0.5876777251184834
Gradient boosting:  0.6289776574136764


### Classification Accuracy
- acturally this is same as score matrix

In [51]:
l_predict = l.predict(x_test)
d_predict = d.predict(x_test)
r_predict = r.predict(x_test)
g_predict = g.predict(x_test)

In [52]:
from sklearn import metrics
print('Logistic Regression Accuracy: ', metrics.accuracy_score(y_test, l_predict))
print('Decision Tree Accuracy: ', metrics.accuracy_score(y_test, d_predict))
print('Random Forest Accuracy: ', metrics.accuracy_score(y_test, r_predict))
print('Gradient Boosting Accuracy: ', metrics.accuracy_score(y_test, g_predict))

Logistic Regression Accuracy:  0.6330399458361544
Decision Tree Accuracy:  0.5172647257955315
Random Forest Accuracy:  0.5876777251184834
Gradient Boosting Accuracy:  0.6289776574136764


## Notes on 4/28/2018

####  first do grid searchCV ( look for difference parameter)
- two ways: 1. regular grid search ( only once)
            2. grid search cv (separate)
####  k-fold cross validation ( cross score) after grid search cv 
####  grident boost classifier

## Grid search

Grid-searching is the process of scanning the data to configure optimal parameters for a given model. Depending on the type of model utilized, certain parameters are necessary. Grid-searching does NOT only apply to one model type. Grid-searching can be applied across machine learning to calculate the best parameters to use for any given model. It is important to note that Grid-searching can be extremely computationally expensive and may take your machine quite a long time to run. Grid-Search will build a model on each parameter combination possible. It iterates through every parameter combination and stores a model for each combination. Without further ado, lets jump into some examples and implementation.

In [53]:
# Grid search implementation


In [54]:
# import library
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [55]:
# Instantiating the model
model = DecisionTreeClassifier()

In [56]:
# Establishing the parameters to grid-search
# It is important to note that these parameters change depending on what 
# type of model we are building. Be sure to look up the model specific documentation for paramter explanation

In [57]:
# for DecisionTreeClasifier model

In [58]:
criterion = ['gini','entropy']
max_depth = [1,3,5, None]
splitter = ['best','random']

In [59]:
# setting up the GridSearch. Note how the parameters are wrapped within a dictionary.
grid = GridSearchCV(estimator=model, cv=3, 
                    param_grid=dict(criterion=criterion, max_depth=max_depth, splitter=splitter))

In [60]:
# Fitting the Grid-Search to our Data
grid.fit(x_train, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_depth': [1, 3, 5, None], 'splitter': ['best', 'random']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [61]:
# Depending on the designated parameter for measuring the model, will print the best score throughout the Grid Search
print(grid.best_score_)

0.6509146341463414


In [62]:
# Will print out the best parameters used for the hightest score of the model
print(grid.best_params_)

{'criterion': 'entropy', 'max_depth': 1, 'splitter': 'best'}


In [63]:
bestmodel = DecisionTreeClassifier(criterion = 'entropy', max_depth = 1, splitter = 'random')

In [64]:
bm = bestmodel.fit(x_train, y_train)

In [65]:
y_predict_test = bm.predict(x_test)

In [66]:
bm.score(x_test, y_test)

0.6343940419769803

In [67]:
# grident boosting classification model

Gradient Boosting Algorithm parameter
The overall parameters can be divided into 3 categories:
- Three-specfic Parameters: These affect each individual tree in the model(Min_samples_split, min_sample_leaf,<br>
min_weight_fraction_leaf, Max_depth, max_leaf_nodes, max_features)
- Boosting Parameters: These affect the oosting operation in the model(Learnint_rate, n_estimators, subsample)
- Miscellaneous Parameters: Other parameters for overall functioning Loss, init, random_state, verbose, warm_start,<br> presort
  